### ISSUE TITLE
could you please provide the model converted from .t7

### ISSUE THREAD

**Issue by Luhb** [jcdubron/scnn_pytorch#1]
hello,the pre-trained model  provided by the author of the paper is .t7 , can you tell me how to transfer it into .pth or provide a transfered model,thank you.

**Comment by jcdubron** [comment]
The tool has been uploaded to [tools/t7_to_pth.py](https://github.com/jcdubron/scnn_pytorch/blob/master/tools/t7_to_pth.py). You can check the detailed hierarchy of the original model by Torch7 or as the above tool does. Note that Pytorch 1.0.0 does not support the load_lua function and you'd better run it with Pytorch 0.4.1.
