### ISSUE TITLE
kernelsize

### ISSUE THREAD

**Issue by seawavesY** [jcdubron/scnn_pytorch#15]
First of all, thank you very much for your work.
I am trying to change the dataset to Tusimple. Should I resize the image to (800, 288)?
In addition, what is '  probmap'?
The model output x1 and x2. The size of x1 is [batchsize, 5 , W, H]. Why channel is 5?

**Comment by jcdubron** [comment]
1. The format of Tusimple dataset is different from CULane and you have to transform one as another.
2. 'probmap' is the abbreviation of 'probability maps' in [SCNN](https://arxiv.org/abs/1712.06080).
3. There are five classes, one for background and the other four for different traffic lanes respectively.

**Comment by seawavesY** [comment]
Thanks a lot for your reply. 
`loss1 = F.cross_entropy(predictmaps, probmaps, weight=weight)`
As for Tusimple,how to get the probmaps?

**Comment by jcdubron** [comment]
I recommend [cv::line](https://docs.opencv.org/master/d6/d6e/group__imgproc__draw.html#ga7078a9fae8c7e7d13d24dac2520ae4a2) and some similar functions to transform points into probmaps.
The order of lines should be from left to right and there is a lot of work to be done. Good luck.

**Comment by seawavesY** [comment]
Thanks! I I have completed the annotation of the Tusimple.I got a binary image and an instance segmentation image.They are grayscale images.As for instance segmentation, different lane lines are marked by different gray values. Which one should be treated as probmaps?
What is the probmaps in CULane? 
Thank you again for your reply.

**Comment by jcdubron** [comment]
Different gray values are different classes. The first line is labeled as 1 and the last is labeled as 4.

**Comment by seawavesY** [comment]
Thank you very much ！
