### ISSUE TITLE
How to test arrow and crosswalk?

### ISSUE THREAD

**Issue by earlysleepearlyup** [jcdubron/scnn_pytorch#16]
Hello, I have trained and test your scnn_pytorch successfully.
Now I want to konw how to test the image with arrow and crosswalk. 
Could you please teach me how to test the arrow?
Thank you @jcdubron

**Comment by jcdubron** [comment]
It is a type of traffic scene but not an arrow itself.
You can refer to the [CULane dataset](https://xingangpan.github.io/projects/CULane.html) or [codes](https://github.com/XingangPan/SCNN) provided by the author.

**Comment by earlysleepearlyup** [comment]
Oh, I see, thank you!
