### ISSUE TITLE
Where is prob_dir=args.eval_data_dir+'_labelmap'?

### ISSUE THREAD

**Issue by AbnerCSZ** [jcdubron/scnn_pytorch#3]
In line 145 and 154 in main.py, there is a dir named prob_dir. But I can not find the _labelmap dir in CULane dataset. Could you tell me where is this dir? Thank you very much!

**Comment by jcdubron** [comment]
The folder structure should be modified a little. Refer to list files of CULane for more detail.
```
train           # train images (.jpg)
train_labelmap  # train labelmap (.png)
test            # test images (.jpg)
test_labelmap   # test labelmap (.png)
```
