### ISSUE TITLE
tools/evaluate.py is nou completed

### ISSUE THREAD

**Issue by HongJinZ** [jcdubron/scnn_pytorch#7]
Hello, I am a freshman. When I have the honor to learn your code, I have learned a lot. Given that I have just been involved in deep learning, I can't complete the omission in evaluate.py. So, could you provide me a completed code? I will appreciate your help a lot.

**Comment by jcdubron** [comment]
Although I have finished *evaluate.py* on my own, it may not be compatable with this repository. If you want to figure out the details of evaluation mechanism, I highly recommend the C++ code at [here](https://github.com/XingangPan/SCNN/blob/f941e2b1c5489b670ab300f2188031b19796be78/tools/lane_evaluation/src/evaluate.cpp) which is provided by the author of this paper. Sorry about that.

**Comment by HongJinZ** [comment]
Can you tell me will it work if I convert this C++ code to python. As you say, the evaluate.py may not be compatable with this repository, and then could you provide the code(may be C++) that can come to the result that you showed in github?

**Comment by jcdubron** [comment]
[This line](https://github.com/jcdubron/scnn_pytorch/blob/d018aeb93d0a15cfbfebf4bb87bd5521c0c96003/python/test.py#L47) calls the executable program but not *evaluate.py*. So it works without any other codes.

**Comment by HongJinZ** [comment]
Sorry, I am confused why it sotps every time when it runs to this line. And the error is: 

/bin/sh:c1: ./tools/evaluate:Permission denied

Traceback (most recent call last):

............

subprocess.CallProcessError:Command'./tools/evaluate -a/home/hj/scnn_pytorch -d ./output/lines -i /home/scnn_pytorch -l /home/hj/scnn_pytorch/val_gt.txt -w 30 -t 0.5 -c 1640 -r 590 -f 1' returned non-zero exit status 126.


Could you please tell me how to solve this problem? Thank you very much.

**Comment by jcdubron** [comment]
```chmod +x ./tools/evaluate```

**Comment by HongJinZ** [comment]
Do I need to build a new folder named "evaluate" under tools, and then give it this authority?

**Comment by HongJinZ** [comment]
I‘m so sorry to bother you all the time. But I am really sad of unable to understand the code and solve these problems. So I am in deep appreciation of your help. And I have another question that where the executable program is.

**Comment by jcdubron** [comment]
It's included in *tools* folder.

**Comment by HongJinZ** [comment]
But the tools folder only includes three files as following: __init__.py, t7_to_pth.py, test_result_process.py and a model named vgg_SCNN_DULR_w9.pth. I don't know which one you point to.

**Comment by HongJinZ** [comment]
What's more, the init.py is empty.

**Comment by jcdubron** [comment]
There are four files in *tools* folder in this repository including executable program [*evaluate*](https://github.com/jcdubron/scnn_pytorch/blob/master/tools/evaluate). Please make sure that you have downloaded all these files.

**Comment by HongJinZ** [comment]
Good morning, a fault occurs like this:
error while loading shared libraries: libopencv_core.so.2.4: cannot open shared object file: No such file or directory
Should I install opencv2.4? But the version of my python is 3.7. Are they campatable with each other？ Could you tell me which version of python and opencv is correct.

**Comment by jcdubron** [comment]
You can google these errors about python environment and help yourself.
